# Generated by Django 6.0.1 on 2026-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        # Add individual indexes
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transaction_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account'], name='transaction_account_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_category_idx'),
        ),

        # Add composite indexes for common query patterns
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'account'], name='transaction_date_account_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'category'], name='transaction_date_category_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'category'], name='transaction_account_category_idx'),
        ),
    ]
